version: '3.7'
services:
  grafana:
    image: "grafana/grafana"
    configs:
      - source:  grafana-config
        target: /usr/share/grafana/conf/grafana.ini
    volumes:
      - "./dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
  prometheus:
    image: "prom/prometheus"
    configs:
            - source:  prometheus-config
              target: /etc/prometheus/prometheus.yml
            - source:  prometheus.rules-config
              target: /etc/prometheus/prometheus.rules.yml
    ports:
      - "9090:9090"
  project-dev-kpis:
    image: "soundcloud/project-dev-kpis"
    env_file:
      - "./config/production.env"
    configs:
            - source:  projects-config
              target: /projects.json
    volumes:
      - "/tmp:/tmp"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:80/-/health && echo 'ready'"]
      interval: 10s
      retries: 30
